5_TaskFive/Hospital/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models
{
    public class Patient
    {
        public Patient()
        {
            ArrivalDate = DateTime.Now;
        }
        public int Id { get; set; }
        public int DiagnosisId { get; set; }
        public string Name { get; set; }
        public DateTime ArrivalDate { get; set; }
    }
}

5_TaskFive/Hospital/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hospital.Models;
using Hospital.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Hospital.Controllers
{
    public class PatientController : Controller
    {
        HospitalContext db;
        public PatientController(HospitalContext context)
        {
            this.db = context;
        }
        public IActionResult Index(int? DiagnosisId, int Page = 1, SortState SortOrder = SortState.NameAsc)
        {
            int pageSize = 3;

            List<DiagnosisVM> diagnosesVM = db.Diagnoses
                .Select(d => new DiagnosisVM { Id = d.Id, Title = d.Title })
                .ToList();

            List<PatientVM> patientsVM = new List<PatientVM>();
            foreach (var patient in db.Patients.ToList())
            {
                var e = db.Diagnoses.ToList();
                Diagnosis diagnosis = db.Diagnoses.ToList().Where(di => di.Id == patient.DiagnosisId).FirstOrDefault();
                if (DiagnosisId == null || DiagnosisId == 0 || diagnosis.Id == DiagnosisId)
                    patientsVM.Add(new PatientVM(patient.ArrivalDate) { Id = patient.Id, Name = patient.Name, Diagnosis = diagnosis.Title });
            }


            switch (SortOrder)
            {
                case SortState.NameDesc:
                    patientsVM = patientsVM.OrderByDescending(s => s.Name).ToList();
                    break;
                case SortState.DiagnAsc:
                    patientsVM = patientsVM.OrderBy(s => s.Diagnosis).ToList();
                    break;
                case SortState.DiagnDesc:
                    patientsVM = patientsVM.OrderByDescending(s => s.Diagnosis).ToList();
                    break;
                case SortState.DateAsc:
                    patientsVM = patientsVM.OrderBy(s => s.Lifetime).ToList();
                    break;
                case SortState.DateDesc:
                    patientsVM = patientsVM.OrderByDescending(s => s.Lifetime).ToList();
                    break;
                default:
                    patientsVM = patientsVM.OrderBy(s => s.Name).ToList();
                    break;
            }

            var count = patientsVM.Count();
            var items = patientsVM.Skip((Page - 1) * pageSize).Take(pageSize).ToList();

            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = new PageViewModel(count, Page, pageSize),
                SortViewModel = new SortViewModel(SortOrder),
                FilterViewModel = new FilterViewModel(diagnosesVM, DiagnosisId),
                Patients = items
            };
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Diagnoses = new SelectList(db.Diagnoses.ToList(), "Id", "Title");
            return View();
        }
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public IActionResult Add(AddPatientVM pat)
        {
            if (pat.Name == null)
            {
                return BadRequest();
            }
            db.Patients.Add(new Patient { Name = pat.Name, DiagnosisId = pat.DiagnosisId });
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public IActionResult Delete(int id)
        {
            if (id == 0 || db.Patients.Find(id) == null)
            {
                return NotFound();
            }
            Patient p = db.Patients.Find(id);
            Diagnosis d = db.Diagnoses.ToList().Where(di => di.Id == p.DiagnosisId).FirstOrDefault();
            return View(new PatientVM(p.ArrivalDate) { Id = p.Id, Name = p.Name, Diagnosis = d.Title });
        }
        [HttpPost]
        public IActionResult Delete(PatientVM p)
        {
            db.Patients.Remove(db.Patients.Find(p.Id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

5_TaskFive/Hospital/Views/Patient/Add.cshtml
@{
    ViewData["Title"] = "Add patient";
}
@using Hospital.ViewModels
@using Hospital.Models
@model AddPatientVM

<h2>Form of adding patient</h2>

<p>fill in the following fields:</p>
<form asp-controller="Patient" asp-action="Add" asp-antiforgery="true">
    <div>
        <div>
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" />
        </div>
        <div>
            <label asp-for="DiagnosisId"></label>
            <select asp-for="DiagnosisId" asp-items="ViewBag.Diagnoses"></select>
        </div>
        <div>
            <input type="submit" class="btn btn-success" value="Confirm" />
            <button type="button" class="btn btn-danger">
                <a asp-controller="Patient" asp-action="Index" style="color:inherit">Cancel</a>
            </button>
        </div>
    </div>
</form>

5_TaskFive/Hospital/Views/Patient/Delete.cshtml
@{
    ViewData["Title"] = "Discharge patint";
}

@using Hospital.ViewModels
@using Hospital.Models
@model PatientVM

<h2>Form of discharging from hospital </h2>
<form asp-controller="Patient" asp-action="Delete" asp-antiforgery="true">
    <div>
        <div>
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" value="@Model.Name" disabled />
        </div>
        <div>
            <label asp-for="Diagnosis"></label>
            <input type="text" asp-for="Diagnosis" value="@Model.Diagnosis" disabled />
        </div>
        <div>
            <label asp-for="Lifetime"></label>
            <input type="text" asp-for="Lifetime" value="@Model.Lifetime.Days days  @Model.Lifetime.Hours hours  @Model.Lifetime.Minutes min" disabled />
        </div>
    </div>
    <div>
        <input type="submit" class="btn btn-success" value="Confirm" />
        <button type="button" class="btn btn-danger">
            <a asp-controller="Patient" asp-action="Index" style="color:inherit">Cancel</a>
        </button>
    </div>
</form>

5_TaskFive/Hospital/Views/Patient/Index.cshtml
@{
    ViewData["Title"] = "Patient";
}

@using Hospital.ViewModels
@using Hospital.Models
@model IndexViewModel
Diagnosis
<form class="form-inline">
    <label>Choose diagnosis:</label>
    <select name="DiagnosisId" asp-items="Model.FilterViewModel.diagnoses" class="form-control"></select>
    <input type="submit" />
</form>
<br />
<table class="table">
    <tr>
        <th>
            <a asp-action="Index"
               asp-route-sortOrder="@(Model.SortViewModel.NameSort)"
               asp-route-company="@(Model.FilterViewModel.SelectedDiagnosis)">Name</a>
        </th>
        <th>
            <a asp-action="Index" asp-route-sortOrder="@(Model.SortViewModel.DiagnSort)"
               asp-route-company="@(Model.FilterViewModel.SelectedDiagnosis)">Diagnosis</a>
        </th>
        <th>
            <a asp-action="Index" asp-route-sortOrder="@(Model.SortViewModel.DateSort)"
               asp-route-company="@(Model.FilterViewModel.SelectedDiagnosis)">Lifetime</a>
        </th>
    </tr>
    @foreach (PatientVM p in Model.Patients)
    {
        <tr>
            <td>@p.Name</td>
            <td>@p.Diagnosis</td>
            <td>
                @p.Lifetime.Days days
                @p.Lifetime.Hours hours
                @p.Lifetime.Minutes min
            </td>
            <td><a href="~/Patient/Delete/@p.Id">Discharge from hospital</a></td>
        </tr>
    }
</table>
<br />
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       asp-route-company="@(Model.FilterViewModel.SelectedDiagnosis)"
       asp-route-sortorder="@(Model.SortViewModel.Current)"
       class="btn  btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       asp-route-company="@(Model.FilterViewModel.SelectedDiagnosis)"
       asp-route-sortorder="@(Model.SortViewModel.Current)"
       class="btn btn-outline-dark">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}
<br />
<div class="container">
    <div class="row mt-2">
        <div class="col-3">
            <button type="button" class="btn btn-primary">
                <a href="~/Patient/Add/" style="color: inherit">Add new</a>
            </button>
        </div>
    </div>
</div>